Generando Error en Analisis SAST

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -9,33 +9,27 @@ jobs:
   JTRPipeline:
     runs-on: ubuntu-latest
     steps:
-      # 1. Clonar repositorio completo
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
+        - name: Checkout repository
+          uses: actions/checkout@v4
 
-      # 2.0 Validar existencia o crear proyecto en SonarCloud
-      - name: Validando existencia de Proyecto en Sonarcloud
-        id: validateProjectSonar
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-          curl -s -X POST -u "$SONAR_TOKEN:" \
-            'https://sonarcloud.io/api/projects/create' \
-            -d "name=${{ github.event.repository.name }}" \
-            -d "organization=juliotabilo" \
-            -d "project=${{ github.event.repository.name }}" \
-            -d "visibility=public" || true
-          echo "Proyecto creado o ya existente en SonarCloud"
-
-      # 2.1 Análisis SonarCloud (SAST)
-      - name: SonarCloud
-        uses: SonarSource/sonarcloud-github-action@v5.0.0
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        with:
-          args: -Dsonar.qualitygate.wait=true
-
-
+        #- name: Imprimir Hola Mundo
+          #run: echo "Hola Mundo desde GitHub Actions (Mi primer Job)"
+        
+        - name: Validando existencia de Proyecto en Sonarcloud
+          id: validateProjectSonar
+          run: |
+            curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{github.event.repository.name}}' -d 'organization=juliotabilo' -d 'project=${{github.event.repository.name}}' -d 'visibility=public'
+            if [ $? -eq 0 ]; then
+              echo "Proyecto creado o ya existe en SonarCloud"
+              curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{github.event.repository.name}}'
+            else
+              echo "Error al crear el proyecto en SonarCloud"
+              exit 1
+            fi
+        - name: Analisis SonarCloud
+          uses: SonarSource/sonarcloud-github-action@master
+          env:
+            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          with:
+            args: -Dsonar.qualitygate.wait=true
